#############################################################################
# Makefile for building: mesh.app/Contents/MacOS/mesh
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  mesh.pro
# Template: app
# Command: /Users/XiangSun/Qt5.4.1/5.4/clang_64/bin/qmake -o Makefile mesh.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I. -I/src -I/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers -I/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers -I/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers -I/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtXml.framework/Versions/5/Headers -I/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers -I.moc -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/macx-clang -F/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib
QMAKE         = /Users/XiangSun/Qt5.4.1/5.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = mesh1.0.0
DISTDIR = /Users/XiangSun/Documents/Program/libQGLViewer-2.6.1/examples/mesh/.obj/mesh1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib -F/Users/XiangSun/Library/Frameworks -framework QGLViewer -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtXml -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		viewer.cpp \
		meshobject.cpp \
		renderer.cpp .moc/moc_mainwindow.cpp
OBJECTS       = .obj/main.o \
		.obj/mainwindow.o \
		.obj/viewer.o \
		.obj/meshobject.o \
		.obj/renderer.o \
		.obj/moc_mainwindow.o
DIST          = /Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/spec_pre.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/qdevice.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/device_config.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/shell-unix.conf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/unix.conf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/mac.conf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/macx.conf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/gcc-base.conf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/clang.conf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/clang-mac.conf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/qconfig.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/qt_functions.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/qt_config.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/spec_post.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/default_pre.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/resolve_config.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/default_post.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/warn_on.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/qt.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/resources.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/moc.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/uic.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/unix/thread.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/mac/rez.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/exceptions.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/yacc.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/lex.prf \
		mesh.pro mainwindow.h \
		viewer.h \
		meshobject.h \
		renderer.h main.cpp \
		mainwindow.cpp \
		viewer.cpp \
		meshobject.cpp \
		renderer.cpp
QMAKE_TARGET  = mesh
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = mesh.app/Contents/MacOS/mesh

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d mesh.app/Contents/MacOS/ || mkdir -p mesh.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mesh.pro /Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/macx-clang/qmake.conf /Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/spec_pre.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/qdevice.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/device_config.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/shell-unix.conf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/unix.conf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/mac.conf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/macx.conf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/gcc-base.conf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/clang.conf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/clang-mac.conf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/qconfig.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/qt_functions.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/qt_config.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/spec_post.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/default_pre.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/resolve_config.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/default_post.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/warn_on.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/qt.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/resources.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/moc.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/uic.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/unix/thread.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/mac/rez.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/exceptions.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/yacc.prf \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/lex.prf \
		mesh.pro \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/QGLViewer.prl \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtXml.framework/QtXml.prl
	$(QMAKE) -o Makefile mesh.pro
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/spec_pre.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/qdevice.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/device_config.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/shell-unix.conf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/unix.conf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/mac.conf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/macx.conf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/gcc-base.conf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/clang.conf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/common/clang-mac.conf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/qconfig.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/qt_functions.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/qt_config.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/spec_post.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/default_pre.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/resolve_config.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/default_post.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/mac/sdk.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/mac/default_post.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/warn_on.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/qt.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/resources.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/moc.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/unix/opengl.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/uic.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/unix/thread.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/mac/rez.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/testcase_targets.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/exceptions.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/yacc.prf:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/features/lex.prf:
mesh.pro:
/Users/XiangSun/Library/Frameworks/QGLViewer.framework/QGLViewer.prl:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtXml.framework/QtXml.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile mesh.pro

qmake_all: FORCE

mesh.app/Contents/PkgInfo: 
	@test -d mesh.app/Contents || mkdir -p mesh.app/Contents
	@$(DEL_FILE) mesh.app/Contents/PkgInfo
	@echo "APPL????" >mesh.app/Contents/PkgInfo
mesh.app/Contents/Resources/empty.lproj: 
	@test -d mesh.app/Contents/Resources || mkdir -p mesh.app/Contents/Resources
	@touch mesh.app/Contents/Resources/empty.lproj
	
mesh.app/Contents/Info.plist: 
	@test -d mesh.app/Contents || mkdir -p mesh.app/Contents
	@$(DEL_FILE) mesh.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,sss.mesh,g" -e "s,@ICON@,qglviewer.icns,g" -e "s,@EXECUTABLE@,mesh,g" -e "s,@TYPEINFO@,????,g" /Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/macx-clang/Info.plist.app >mesh.app/Contents/Info.plist
mesh.app/Contents/Resources/qglviewer.icns: icon/qglviewer.icns
	@test -d mesh.app/Contents/Resources/ || mkdir -p mesh.app/Contents/Resources/
	@$(DEL_FILE) mesh.app/Contents/Resources/qglviewer.icns
	@$(COPY_FILE) icon/qglviewer.icns mesh.app/Contents/Resources/qglviewer.icns

all: Makefile \
		mesh.app/Contents/PkgInfo \
		mesh.app/Contents/Resources/empty.lproj \
		mesh.app/Contents/Info.plist \
		mesh.app/Contents/Resources/qglviewer.icns $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h viewer.h meshobject.h renderer.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp viewer.cpp meshobject.cpp renderer.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r mesh.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: .moc/moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/moc_mainwindow.cpp
.moc/moc_mainwindow.cpp: /Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		mainwindow.h
	/Users/XiangSun/Qt5.4.1/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/XiangSun/Qt5.4.1/5.4/clang_64/mkspecs/macx-clang -I/Users/XiangSun/Documents/Program/libQGLViewer-2.6.1/examples/mesh -I/src -I/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Headers -I/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtOpenGL.framework/Headers -I/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtXml.framework/Headers -I/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib mainwindow.h -o .moc/moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		viewer.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/qglviewer.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/camera.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/keyFrameInterpolator.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/quaternion.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/vec.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtXml.framework/Versions/5/Headers/QDomElement \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtXml.framework/Versions/5/Headers/qdom.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/config.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLWidget \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/frame.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/constraint.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QMap \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qmap.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QClipboard \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qclipboard.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h
	/Users/XiangSun/Qt5.4.1/5.4/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

.obj/main.o: main.cpp mainwindow.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o main.cpp

.obj/mainwindow.o: mainwindow.cpp /Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		mainwindow.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		ui_mainwindow.h \
		viewer.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/qglviewer.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/camera.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/keyFrameInterpolator.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/quaternion.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/vec.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtXml.framework/Versions/5/Headers/QDomElement \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtXml.framework/Versions/5/Headers/qdom.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/config.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLWidget \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/frame.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/constraint.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QMap \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qmap.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QClipboard \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qclipboard.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/mainwindow.o mainwindow.cpp

.obj/viewer.o: viewer.cpp mainwindow.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		viewer.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/qglviewer.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/camera.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/keyFrameInterpolator.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/quaternion.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/vec.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtXml.framework/Versions/5/Headers/QDomElement \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtXml.framework/Versions/5/Headers/qdom.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/config.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLWidget \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/frame.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Users/XiangSun/Library/Frameworks/QGLViewer.framework/Versions/2/Headers/constraint.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QMap \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qmap.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QClipboard \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qclipboard.h \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		/Users/XiangSun/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		meshobject.h \
		renderer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/viewer.o viewer.cpp

.obj/meshobject.o: meshobject.cpp meshobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/meshobject.o meshobject.cpp

.obj/renderer.o: renderer.cpp renderer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/renderer.o renderer.cpp

.obj/moc_mainwindow.o: .moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_mainwindow.o .moc/moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

